// Generated by CoffeeScript 1.8.0
(function() {
  "use strict";
  var ApiError, FTClient, NetworkError, base_url, fileChangeMode, fileCopy, fileDelete, fileMove, fileRename, fileUpload, folderChangeMode, folderContent, folderCopy, folderCreate, folderDelete, folderInfo, folderMove, folderRename, onetimeCreate, onetimeInfo, protocol, remoteCreate, remoteDelete, remoteInfo, token, trashcanContent, trashcanEmpty, trashcanRestore, userInfo, userLogin, _do_file_upload, _fldr_ops, _item_method_helper,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  protocol = window.location.href.split('://')[0];

  if (protocol === 'file') {
    protocol = 'http';
  }

  base_url = "" + protocol + "://filestrash.com/api/v1";

  token = '';

  ApiError = (function(_super) {
    __extends(ApiError, _super);

    function ApiError(message) {
      ApiError.__super__.constructor.call(this);
      this.name = 'ApiError';
      this.message = message;
    }

    return ApiError;

  })(Error);

  NetworkError = (function(_super) {
    __extends(NetworkError, _super);

    function NetworkError(message) {
      NetworkError.__super__.constructor.call(this);
      this.name = 'NetworkError';
      this.message = message;
    }

    return NetworkError;

  })(Error);

  _do_file_upload = function(params, upload_url, cb) {
    var form_data, upload_progress, xhr;
    form_data = new FormData();
    form_data.append("file", params.file);
    form_data.append("token", params.token || token);
    upload_progress = function(event) {
      if (event.lengthComputable) {
        if (params.progress_cb && typeof params.progress_cb === 'function') {
          return params.progress_cb(Math.ceil(event.loaded / event.total * 100));
        }
      }
    };
    xhr = new XMLHttpRequest();
    xhr.open("POST", upload_url, true);
    xhr.upload.onprogress = upload_progress;
    if (params.abort_cb && typeof params.abort_cb === 'function') {
      xhr.onabort = params.abort_cb;
    }
    xhr.onreadystatechange = function() {
      var data, response;
      if (xhr.readyState === 4 && xhr.status === 200) {
        data = JSON.parse(xhr.responseText);
        response = data.response;
        if (data.status === 200) {
          if (cb && typeof cb === 'function') {
            return cb(null, data.response.file);
          }
        } else {
          if (cb && typeof cb === 'function') {
            return cb(new ApiError("" + data.details + "(" + data.status + ")"));
          }
        }
      } else if (xhr.readyState === 4 && xhr.status !== 200) {
        if (cb && typeof cb === 'function') {
          return cb(new NetworkError("" + status + "(" + xhr.status + ")"));
        }
      }
    };
    xhr.send(form_data);
    if (params.upload_xhr_available && typeof params.upload_xhr_available === 'function') {
      return params.upload_xhr_available(xhr);
    }
  };

  _fldr_ops = ['info', 'content', 'create', 'rename'];

  _item_method_helper = function(itype, method, params, response_field, cb) {
    var k, params_str, v, xhr;
    params.token = params.token || token;
    params_str = '';
    for (k in params) {
      v = params[k];
      if (typeof v !== 'function') {
        params_str += "" + k + "=" + (encodeURIComponent(v)) + "&";
      }
    }
    xhr = new XMLHttpRequest();
    xhr.open("GET", "" + base_url + "/" + itype + "/" + method + "?" + params_str, true);
    xhr.onreadystatechange = function() {
      var data, result, twolevel;
      if (xhr.readyState === 4 && xhr.status === 200) {
        data = JSON.parse(xhr.responseText);
        if (data.status === 200 && data.response) {
          result = response_field ? data.response[response_field] : data.response;
          twolevel = false;
          if (itype === 'user' && method === 'login') {
            token = data.response.token;
          } else if (itype === 'file' && method === 'upload') {
            if (data.response.upload_url) {
              twolevel = true;
              _do_file_upload(params, data.response.upload_url, cb);
            }
          }
          if (cb && typeof cb === 'function' && (!twolevel)) {
            return cb(null, result);
          }
        } else {
          if (cb && typeof cb === 'function') {
            return cb(new ApiError("" + (data != null ? data.details : void 0) + "(" + (data != null ? data.status : void 0) + ")"));
          }
        }
      } else if (xhr.readyState === 4 && xhr.status !== 200) {
        if (cb && typeof cb === 'function') {
          return cb(new NetworkError("" + status + "(" + xhr.status + ")"));
        }
      }
    };
    return xhr.send();
  };

  userLogin = function(login, password, cb) {
    return _item_method_helper('user', 'login', {
      login: login,
      password: password
    }, 'user', cb);
  };

  userInfo = function(cb) {
    return _item_method_helper('user', 'info', {}, 'user', cb);
  };

  fileUpload = function(name, hash, size, file, options, cb) {
    var args, params;
    params = {};
    args = Array.prototype.slice.call(arguments);
    cb = args.pop();
    if (args.length === 5) {
      params = options;
    }
    params.name = name;
    params.hash = hash;
    params.size = size;
    params.file = file;
    return _item_method_helper('file', 'upload', params, 'file', cb);
  };

  fileRename = function(file_id, name, cb) {
    var params;
    params = {
      file_id: file_id,
      name: name
    };
    return _item_method_helper('file', 'rename', params, 'file', cb);
  };

  fileDelete = function(file_id, cb) {
    var params;
    params = {
      file_id: file_id
    };
    return _item_method_helper('file', 'delete', params, 'result', cb);
  };

  fileCopy = function(file_id, folder_id_dest, cb) {
    var params;
    params = {
      file_id: file_id,
      folder_id_dest: folder_id_dest
    };
    return _item_method_helper('file', 'copy', params, 'result', cb);
  };

  fileMove = function(file_id, folder_id_dest, cb) {
    var params;
    params = {
      file_id: file_id,
      folder_id_dest: folder_id_dest
    };
    return _item_method_helper('file', 'move', params, 'result', cb);
  };

  fileChangeMode = function(file_id, mode, cb) {
    var params;
    params = {
      file_id: file_id,
      mode: mode
    };
    return _item_method_helper('file', 'change_mode', params, 'file', cb);
  };

  folderInfo = function(options, cb) {
    var args, params;
    params = {};
    args = Array.prototype.slice.call(arguments);
    cb = args.pop();
    if (args.length === 1) {
      params = options;
    }
    return _item_method_helper('folder', 'info', params, 'folder', cb);
  };

  folderContent = function(options, cb) {
    var args, params;
    params = {};
    args = Array.prototype.slice.call(arguments);
    cb = args.pop();
    if (args.length === 1) {
      params = options;
    }
    return _item_method_helper('folder', 'content', params, 'folder', cb);
  };

  folderCreate = function(name, options, cb) {
    var args, k, params, v;
    params = {
      name: name
    };
    args = Array.prototype.slice.call(arguments);
    cb = args.pop();
    if (args.length === 2) {
      for (k in options) {
        v = options[k];
        params[k] = v;
      }
    }
    return _item_method_helper('folder', 'create', params, 'folder', cb);
  };

  folderRename = function(folder_id, name, cb) {
    var params;
    params = {
      name: name,
      folder_id: folder_id
    };
    return _item_method_helper('folder', 'rename', params, 'folder', cb);
  };

  folderDelete = function(folder_id, cb) {
    var params;
    params = {
      folder_id: folder_id
    };
    return _item_method_helper('folder', 'delete', params, 'result', cb);
  };

  folderCopy = function(folder_id, folder_id_dest, cb) {
    var params;
    params = {
      folder_id: folder_id,
      folder_id_dest: folder_id_dest
    };
    return _item_method_helper('folder', 'copy', params, 'result', cb);
  };

  folderMove = function(folder_id, folder_id_dest, cb) {
    var params;
    params = {
      folder_id: folder_id,
      folder_id_dest: folder_id_dest
    };
    return _item_method_helper('folder', 'move', params, 'result', cb);
  };

  folderChangeMode = function(folder_id, mode, cb) {
    var params;
    params = {
      folder_id: folder_id,
      mode: mode
    };
    return _item_method_helper('folder', 'change_mode', params, 'folder', cb);
  };

  trashcanContent = function(cb) {
    return _item_method_helper('trashcan', 'content', {}, null, cb);
  };

  trashcanEmpty = function(options, cb) {
    var args, params;
    params = {};
    args = Array.prototype.slice.call(arguments);
    cb = args.pop();
    if (args.length === 1) {
      params = options;
    }
    return _item_method_helper('trashcan', 'empty', params, 'result', cb);
  };

  trashcanRestore = function(options, cb) {
    var args, params;
    params = {};
    args = Array.prototype.slice.call(arguments);
    cb = args.pop();
    if (args.length === 1) {
      params = options;
    }
    return _item_method_helper('trashcan', 'restore', params, 'result', cb);
  };

  remoteCreate = function(url, options, cb) {
    var args, params;
    params = {};
    args = Array.prototype.slice.call(arguments);
    cb = args.pop();
    if (args.length === 2) {
      params = options;
    }
    params.url = url;
    return _item_method_helper('remote', 'create', params, '', cb);
  };

  remoteDelete = function(job_id, cb) {
    var params;
    params = {
      job_id: job_id
    };
    return _item_method_helper('remote', 'delete', params, 'result', cb);
  };

  remoteInfo = function(options, cb) {
    var args, params;
    params = {};
    args = Array.prototype.slice.call(arguments);
    cb = args.pop();
    if (args.length === 1) {
      params = options;
    }
    return _item_method_helper('remote', 'info', params, '', cb);
  };

  onetimeCreate = function(file_id, options, cb) {
    var args, params;
    params = {};
    args = Array.prototype.slice.call(arguments);
    cb = args.pop();
    if (args.length === 2) {
      params = options;
    }
    params.file_id = file_id;
    return _item_method_helper('one_time_download', 'create', params, 'download', cb);
  };

  onetimeInfo = function(options, cb) {
    var args, params;
    params = {};
    args = Array.prototype.slice.call(arguments);
    cb = args.pop();
    if (args.length === 1) {
      params = options;
    }
    return _item_method_helper('one_time_download', 'info', params, '', cb);
  };

  window.FTClient = FTClient = {
    _setToken: function(newToken) {
      return token = newToken;
    },
    _setBaseUrl: function(newBaseUrl) {
      return base_url = newBaseUrl;
    },
    ApiError: ApiError,
    NetworkError: NetworkError,
    userLogin: userLogin,
    userInfo: userInfo,
    fileUpload: fileUpload,
    fileRename: fileRename,
    fileDelete: fileDelete,
    fileMove: fileMove,
    fileCopy: fileCopy,
    fileChangeMode: fileChangeMode,
    folderInfo: folderInfo,
    folderContent: folderContent,
    folderCreate: folderCreate,
    folderRename: folderRename,
    folderDelete: folderDelete,
    folderCopy: folderCopy,
    folderMove: folderMove,
    folderChangeMode: folderChangeMode,
    trashcanContent: trashcanContent,
    trashcanEmpty: trashcanEmpty,
    trashcanRestore: trashcanRestore,
    remoteCreate: remoteCreate,
    remoteDelete: remoteDelete,
    remoteInfo: remoteInfo,
    onetimeCreate: onetimeCreate,
    onetimeInfo: onetimeInfo
  };

}).call(this);
